<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="imu_joint" type="fixed">
        <parent link="chassis"/>
        <child link="robot_imu"/>
        <origin xyz="${chassis_length/2 - 0.15285} 0 0" rpy="0 0 0"/>
    </joint>

    <link name="robot_imu">

    </link>

    <gazebo reference="robot_imu">
        <material>Gazebo/Black</material>
    </gazebo>


</robot>