twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : /rmp/cmd_vel
        timeout : 0.5
        priority: 10
      tracker:
        topic   : /rmp/cmd_vel_tracker
        timeout : 0.5
        priority: 20
      joystick:
        topic   : /rmp/cmd_vel_joy
        timeout : 0.5
        priority: 100